# Generated by Django 3.1.6 on 2021-09-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('acount_no', models.PositiveIntegerField()),
                ('Bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bioinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('DateOfBirth', models.DateField()),
                ('Homeaddress', models.CharField(max_length=50)),
                ('OffieNumber', models.PositiveIntegerField()),
                ('mobile_no', models.PositiveIntegerField()),
                ('Pin_no', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=100)),
                ('physical_add', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('estate', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=100)),
                ('livedthrere', models.CharField(max_length=100)),
                ('Houseowned', models.CharField(choices=[('No', 'No'), ('yes', 'yes')], max_length=3)),
                ('martial_status', models.CharField(choices=[('single', 'single'), ('married', 'married'), ('window', 'window'), ('other', 'other')], max_length=7)),
                ('No_dependents', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofbusiness', models.CharField(max_length=100)),
                ('yrsoperation', models.PositiveIntegerField()),
                ('Businessincome', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100)),
                ('physical_add', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employmenterms', models.CharField(choices=[('Peranent', 'Peranent'), ('casual', 'casual'), ('Contract', 'Contract')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.CharField(choices=[('normal', 'normal'), ('Development', 'Development'), ('Development', 'Development'), ('school fee', 'school fee')], max_length=16)),
                ('Purposeofloan', models.TextField()),
                ('amountapplied', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('amount_advanced', models.PositiveIntegerField()),
                ('date_granted', models.DateField()),
                ('Repayment_period', models.PositiveIntegerField()),
                ('Outstanding_balance', models.PositiveIntegerField()),
            ],
        ),
    ]
