# Generated by Django 3.1.6 on 2021-09-12 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenege', '0002_auto_20210912_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codechallenege.bioinfo'),
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codechallenege.bioinfo'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codechallenege.bioinfo'),
        ),
        migrations.AlterField(
            model_name='otherloans',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codechallenege.bioinfo'),
        ),
    ]
