# Generated by Django 3.1.6 on 2021-09-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenege', '0003_auto_20210912_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codechallenege.bioinfo'),
        ),
    ]
