# Generated by Django 3.1.6 on 2021-09-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenege', '0004_auto_20210912_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='bio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessdetails', to='codechallenege.bioinfo'),
        ),
    ]
